[2025-04-06 07:10:57,190] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2025-04-06T07:10:44.084835+00:00 [queued]>
[2025-04-06 07:10:57,195] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2025-04-06T07:10:44.084835+00:00 [queued]>
[2025-04-06 07:10:57,195] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 07:10:57,195] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-04-06 07:10:57,195] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-04-06 07:10:57,213] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): training_model> on 2025-04-06 07:10:44.084835+00:00
[2025-04-06 07:10:57,221] {standard_task_runner.py:52} INFO - Started process 6194 to run task
[2025-04-06 07:10:57,224] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'training_model', 'manual__2025-04-06T07:10:44.084835+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpz83zjwog', '--error-file', '/tmp/tmp5sj8n2q6']
[2025-04-06 07:10:57,224] {standard_task_runner.py:80} INFO - Job 35: Subtask training_model
[2025-04-06 07:10:57,264] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2025-04-06T07:10:44.084835+00:00 [running]> on host c6537eab7989
[2025-04-06 07:10:57,319] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=training_model
AIRFLOW_CTX_EXECUTION_DATE=2025-04-06T07:10:44.084835+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-04-06T07:10:44.084835+00:00
[2025-04-06 07:10:57,690] {logging_mixin.py:115} WARNING - 2025/04/06 07:10:57 INFO mlflow.tracking.fluent: Experiment with name 'Lead_Scoring_Training_Pipeline' does not exist. Creating a new experiment.
[2025-04-06 07:11:02,266] {logging_mixin.py:115} WARNING - /opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2025-04-06 07:11:05,907] {logging_mixin.py:115} WARNING - Successfully registered model 'LightGBM'.
[2025-04-06 07:11:05,944] {logging_mixin.py:115} WARNING - 2025/04/06 07:11:05 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: LightGBM, version 1
[2025-04-06 07:11:05,944] {logging_mixin.py:115} WARNING - Created version '1' of model 'LightGBM'.
[2025-04-06 07:11:06,138] {python.py:173} INFO - Done. Returned value was: None
[2025-04-06 07:11:06,145] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=Lead_scoring_training_pipeline, task_id=training_model, execution_date=20250406T071044, start_date=20250406T071057, end_date=20250406T071106
[2025-04-06 07:11:06,196] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-04-06 07:11:06,204] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
